services:

   php:
     build:
       context: .
       args:
         user: '1000'
         uid: '1000'
     container_name: php
     tty: true
     volumes:
       - ./:/var/www/html
     networks:
       - desafio_net

   nginx:
     image: nginx:stable-alpine
     container_name: nginx
     tty: true
     ports:
       - "8002:80"
       - "445:443"
     volumes:
       - ./:/var/www/html
       - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
     depends_on:
       - db
       - php
     networks:
       - desafio_net

   db:
     build: ./docker/mysql/.
     container_name: mysql
     environment:
       - MYSQL_ALLOW_EMPTY_PASSWORD=yes
     networks:
       - desafio_net
     ports:
       - "3308:3306"
     volumes:
       - ./docker/mysql/files:/var/lib/mysql
  
   redis:
        image: 'redis:alpine'
        ports:
          - "6379:6379"
        networks:
          - desafio_net
        healthcheck:
          test: ["CMD", "redis-cli", "ping"]

networks:
  desafio_net: